//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable.
        /// </summary>
        internal static string BtnText_Disable {
            get {
                return ResourceManager.GetString("BtnText_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable.
        /// </summary>
        internal static string BtnText_Enable {
            get {
                return ResourceManager.GetString("BtnText_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede habilitar debido al error: .
        /// </summary>
        internal static string CanNotEnableMsg {
            get {
                return ResourceManager.GetString("CanNotEnableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgDisabledNetworkAdapter {
            get {
                object obj = ResourceManager.GetObject("ImgDisabledNetworkAdapter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgEnabledNetworkAdapter {
            get {
                object obj = ResourceManager.GetObject("ImgEnabledNetworkAdapter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas accesar como administrador .
        /// </summary>
        internal static string MsgElevatedRequire {
            get {
                return ResourceManager.GetString("MsgElevatedRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descontectado.
        /// </summary>
        internal static string NetConnectionStatus0 {
            get {
                return ResourceManager.GetString("NetConnectionStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectandose.
        /// </summary>
        internal static string NetConnectionStatus1 {
            get {
                return ResourceManager.GetString("NetConnectionStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autentificación fallida.
        /// </summary>
        internal static string NetConnectionStatus10 {
            get {
                return ResourceManager.GetString("NetConnectionStatus10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección invalida.
        /// </summary>
        internal static string NetConnectionStatus11 {
            get {
                return ResourceManager.GetString("NetConnectionStatus11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales Requeridas.
        /// </summary>
        internal static string NetConnectionStatus12 {
            get {
                return ResourceManager.GetString("NetConnectionStatus12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectado.
        /// </summary>
        internal static string NetConnectionStatus2 {
            get {
                return ResourceManager.GetString("NetConnectionStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectandose.
        /// </summary>
        internal static string NetConnectionStatus3 {
            get {
                return ResourceManager.GetString("NetConnectionStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hardware no presente.
        /// </summary>
        internal static string NetConnectionStatus4 {
            get {
                return ResourceManager.GetString("NetConnectionStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hardware deshabilitado.
        /// </summary>
        internal static string NetConnectionStatus5 {
            get {
                return ResourceManager.GetString("NetConnectionStatus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Malfuncionamiento de hardware.
        /// </summary>
        internal static string NetConnectionStatus6 {
            get {
                return ResourceManager.GetString("NetConnectionStatus6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo desconectado.
        /// </summary>
        internal static string NetConnectionStatus7 {
            get {
                return ResourceManager.GetString("NetConnectionStatus7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autenticando.
        /// </summary>
        internal static string NetConnectionStatus8 {
            get {
                return ResourceManager.GetString("NetConnectionStatus8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autentificación excitosa .
        /// </summary>
        internal static string NetConnectionStatus9 {
            get {
                return ResourceManager.GetString("NetConnectionStatus9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto final Dispositivos.
        /// </summary>
        internal static string OneCodeCaption {
            get {
                return ResourceManager.GetString("OneCodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El adaptador esta siendo deshabilitado, espere-.
        /// </summary>
        internal static string ProgressTextDisableEnd {
            get {
                return ResourceManager.GetString("ProgressTextDisableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El adaptador esta siendo habilitado, espere-.
        /// </summary>
        internal static string ProgressTextEnableEnd {
            get {
                return ResourceManager.GetString("ProgressTextEnableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adaptador de Red:.
        /// </summary>
        internal static string StatusTextBegin {
            get {
                return ResourceManager.GetString("StatusTextBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido  deshailitar..
        /// </summary>
        internal static string StatusTextFailDisableEnd {
            get {
                return ResourceManager.GetString("StatusTextFailDisableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido habilitar .
        /// </summary>
        internal static string StatusTextFailEnableEnd {
            get {
                return ResourceManager.GetString("StatusTextFailEnableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de adaptadores de red encontardos:.
        /// </summary>
        internal static string StatusTextInitial {
            get {
                return ResourceManager.GetString("StatusTextInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha sido desabilitado con éxito!.
        /// </summary>
        internal static string StatusTextSuccessDisableEnd {
            get {
                return ResourceManager.GetString("StatusTextSuccessDisableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha sido habilitado con éxito!.
        /// </summary>
        internal static string StatusTextSuccessEnableEnd {
            get {
                return ResourceManager.GetString("StatusTextSuccessEnableEnd", resourceCulture);
            }
        }
    }
}
